project_id = "ikjkkakphhpogjkrkazv"

[functions]
  [functions.analyze-match]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-tutorial-push]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
